export const propertiesData = {
  properties: [
    {
      id: "prop1",
      type: "House",
      bedrooms: 3,
      price: 750000,
      tenure: "Freehold",
      description:
        "Attractive three bedroom semi-detached family home situated within 0.5 miles of Petts Wood station with fast trains to London...",
      location: "Petts Wood Road, Petts Wood, Orpington BR5",
      picture: "images/prop1pic1small.jpg",
      picturePanel: [
        "images/prop1pic1small.jpg",
        "images/prop1pic2small.jpg",
        "images/prop1pic3small.jpg",
      ],
      url: "properties/prop1.html",
      added: {
        month: "October",
        day: 12,
        year: 2022,
      },
    },
    {
      id: "prop2",
      type: "Flat",
      bedrooms: 2,
      price: 399995,
      tenure: "Freehold",
      description:
        "Presented in excellent decorative order throughout is this two double bedroom, two bathroom, garden flat...",
      location: "Crofton Road Orpington BR6",
      picture: "images/prop2pic1small.png",
      picturePanel: [
        "images/prop1pic1small.jpg",
        "images/prop1pic2small.jpg",
        "images/prop1pic3small.jpg",
      ],
      url: "properties/prop2.html",
      added: {
        month: "September",
        day: 14,
        year: 2022,
      },
    },
    {
      id: "prop3",
      type: "Apartment",
      bedrooms: 1,
      price: 250000,
      tenure: "Leasehold",
      description:
        "Modern one-bedroom apartment located within walking distance of Bromley town center and Bromley South station.",
      location: "High Street, Bromley BR1",
      picture: "images/prop3pic1small.jpg",
      picturePanel: ["images/prop3pic1small.jpg", "images/prop3pic2small.jpg"],
      url: "properties/prop3.html",
      added: {
        month: "November",
        day: 3,
        year: 2022,
      },
    },
    {
      id: "prop4",
      type: "House",
      bedrooms: 4,
      price: 975000,
      tenure: "Freehold",
      description:
        "Spacious four-bedroom detached family home with a large garden, garage, and driveway parking.",
      location: "Farnborough Village, Orpington BR6",
      picture: "images/prop4pic1small.png",
      picturePanel: ["images/prop4pic1small.png", "images/prop4pic2small.png"],
      url: "properties/prop4.html",
      added: {
        month: "August",
        day: 21,
        year: 2022,
      },
    },
    {
      id: "prop5",
      type: "Bungalow",
      bedrooms: 3,
      price: 600000,
      tenure: "Freehold",
      description:
        "Charming three-bedroom bungalow with a modern kitchen, open-plan living, and a beautiful garden.",
      location: "Chislehurst Road, Chislehurst BR7",
      picture: "images/prop5pic1small.jpg",
      picturePanel: ["images/prop5pic1small.jpg", "images/prop5pic2small.jpg"],
      url: "properties/prop5.html",
      added: {
        month: "July",
        day: 7,
        year: 2022,
      },
    },
    {
      id: "prop6",
      type: "Flat",
      bedrooms: 1,
      price: 310000,
      tenure: "Leasehold",
      description:
        "Bright and airy one-bedroom flat with an open-plan living space, situated close to local amenities.",
      location: "Penge High Street, London SE20",
      picture: "images/prop6pic1small.jpg",
      picturePanel: ["images/prop6pic1small.jpg", "images/prop6pic2small.jpg"],
      url: "properties/prop6.html",
      added: {
        month: "June",
        day: 15,
        year: 2022,
      },
    },
    {
      id: "prop7",
      type: "House",
      bedrooms: 5,
      price: 1250000,
      tenure: "Freehold",
      description:
        "Luxury five-bedroom detached house with a large garden, modern interiors, and a double garage.",
      location: "Sundridge Park, Bromley BR1",
      picture: "images/prop7pic1small.jpg",
      picturePanel: [
        "images/prop7pic1small.jpg",
        "images/prop7pic2small.jpg",
        "images/prop7pic3small.jpg",
      ],
      url: "properties/prop7.html",
      added: {
        month: "May",
        day: 23,
        year: 2022,
      },
    },
    {
      id: "prop8",
      type: "Apartment",
      bedrooms: 2,
      price: 420000,
      tenure: "Leasehold",
      description:
        "Well-presented two-bedroom apartment with a private balcony and parking space.",
      location: "Beckenham Lane, Beckenham BR3",
      picture: "images/prop8pic1small.png",
      picturePanel: ["images/prop8pic1small.png", "images/prop8pic2small.png"],
      url: "properties/prop8.html",
      added: {
        month: "April",
        day: 5,
        year: 2022,
      },
    },
    {
      id: "prop9",
      type: "Flat",
      bedrooms: 3,
      price: 475000,
      tenure: "Leasehold",
      description:
        "Spacious three-bedroom flat with a modern kitchen, en-suite master bedroom, and close proximity to parks.",
      location: "Sidcup Hill, Sidcup DA14",
      picture: "images/prop9pic1small.jpg",
      picturePanel: ["images/prop9pic1small.jpg", "images/prop9pic2small.jpg"],
      url: "properties/prop9.html",
      added: {
        month: "March",
        day: 30,
        year: 2022,
      },
    },
    {
      id: "prop10",
      type: "House",
      bedrooms: 6,
      price: 1850000,
      tenure: "Freehold",
      description:
        "Stunning six-bedroom period property with character features, extensive gardens, and ample parking.",
      location: "Shoreham Village, Sevenoaks TN14",
      picture: "images/prop10pic1small.png",
      picturePanel: [
        "images/prop10pic1small.png",
        "images/prop10pic2small.png",
        "images/prop10pic3small.png",
      ],
      url: "properties/prop10.html",
      added: {
        month: "February",
        day: 18,
        year: 2022,
      },
    },
  ],
};
