export const propertiesData = {
  properties: [
    {
      id: "prop1",
      type: "House",
      title: "Madison Main Street Retreat Dogs Welcome",
      bedrooms: 3,
      price: 750000,
      tenure: "Freehold",
      description:
        "Attractive three bedroom semi-detached family home situated within 0.5 miles of Petts Wood station with fast trains to London...",
      location: "Petts Wood Road, Petts Wood, Orpington BR5",
      picture: "images/page-images/1/1.1.jpg",
      picturePanel: [
        "images/page-images/1/1.1.jpg",
        "images/page-images/1/1.2.jpg",
        "images/page-images/1/1.3.jpg",
        "images/page-images/1/1.4.jpg",
        "images/page-images/1/1.5.jpg",
        "images/page-images/1/1.6.jpg",
        "images/page-images/1/1.7.jpg",
        "images/page-images/1/1.8.jpg",
        "images/page-images/1/1.9.jpg",
        "images/page-images/1/1.10.jpg",
        "images/page-images/1/1.11.jpg",
        "images/page-images/1/1.12.jpg",
        "images/page-images/1/1.13.jpg",
      ],
      url: "properties/prop1.html",
      added: {
        month: "October",
        day: 12,
        year: 2022,
      },
    },
    {
      id: "prop2",
      type: "Flat",
      title: "Madison Main Street Retreat Dogs Welcome",
      bedrooms: 2,
      price: 399995,
      tenure: "Freehold",
      description:
        "Presented in excellent decorative order throughout is this two double bedroom, two bathroom, garden flat...",
      location: "Crofton Road Orpington BR6",
      picture: "images/page-images/10/10.1.jpg",
      picturePanel: [
        "images/page-images/10/10.1.jpg",
        "images/page-images/10/10.2.jpg",
        "images/page-images/10/10.3.jpg",
      ],
      url: "properties/prop2.html",
      added: {
        month: "September",
        day: 14,
        year: 2022,
      },
    },
    {
      id: "prop3",
      type: "Apartment",
      title: "Modern Apartment in Bromley Town Center",
      bedrooms: 1,
      price: 250000,
      tenure: "Leasehold",
      description:
        "Modern one-bedroom apartment located within walking distance of Bromley town center and Bromley South station.",
      location: "High Street, Bromley BR1",
      picture: "images/page-images/3/3.4.jpg",
      picturePanel: [
        "images/page-images/3/3.1.jpg",
        "images/page-images/3/3.2.jpg",
        "images/page-images/3/3.3.jpg",
        "images/page-images/3/3.4.jpg",
        "images/page-images/3/3.5.jpg",
      ],
      url: "properties/prop3.html",
      added: {
        month: "November",
        day: 3,
        year: 2022,
      },
    },
    {
      id: "prop4",
      type: "House",
      bedrooms: 4,
      price: 975000,
      title: "East Main Lofts - Farmhouse 204",
      tenure: "Freehold",
      description:
        "East Main Lofts - Farmhouse 204 offers accommodation in Madison, 25 km from General Butler State Park. The apartment also has 1 bathroom. The accommodation is non-smoking. The nearest airport is Louisville International Airport, 88 km from the apartment.",
      location: "323 East Main Street, Madison, IN 47250, United States",
      picture: "images/page-images/4/4.1.jpg",
      picturePanel: [
        "images/page-images/4/4.1.jpg",
        "images/page-images/4/4.2.jpg",
        "images/page-images/4/4.3.jpg",
        "images/page-images/4/4.4.jpg",
        "images/page-images/4/4.5.jpg",
      ],
      url: "properties/prop4.html",
      added: {
        month: "August",
        day: 21,
        year: 2022,
      },
    },
    {
      id: "prop5",
      type: "Bungalow",
      bedrooms: 3,
      title: "Beautiful Bungalow on Main",
      price: 600000,
      tenure: "Freehold",
      description:
        "Beautiful Bungalow on Main is located in Madison. Both free WiFi and parking on-site are accessible at the holiday home free of charge. The property is non-smoking and is situated 25 km from General Butler State Park. The spacious holiday home features 2 separate bedrooms, 2 bathrooms, a fully equipped kitchen with a dining area and dishwasher, and a living room with a flat-screen TV. Featuring air conditioning, this unit has a dressing room and a fireplace. For added privacy, the accommodation features a private entrance. The nearest airport is Louisville International Airport, 88 km from Beautiful Bungalow on Main.",
      location: "605 East Main Street, Madison, IN 47250, United States",
      picture: "images/page-images/2/2.1.jpg",
      picturePanel: [
        "images/page-images/2/2.1.jpg",
        "images/page-images/2/2.2.jpg",
        "images/page-images/2/2.3.jpg",
        "images/page-images/2/2.4.jpg",
        "images/page-images/2/2.5.jpg",
        "images/page-images/2/2.6.jpg",
      ],
      url: "properties/prop5.html",
      added: {
        month: "July",
        day: 7,
        year: 2022,
      },
    },
    {
      id: "prop6",
      type: "Flat",
      title: "Black Pearl Stays - Saltburn Apartments",
      bedrooms: 1,
      price: 310000,
      tenure: "Leasehold",
      description:
        "Bright and airy one-bedroom flat with an open-plan living space, situated close to local amenities.",
      location:
        "1 Pearl Street Black Pearl Apartments, Saltburn-by-the-Sea, TS12 1DU, United Kingdom SE20",
      picture: "images/page-images/5/5.1.jpg",
      picturePanel: [
        "images/page-images/5/5.1.jpg",
        "images/page-images/5/5.2.jpg",
        "images/page-images/5/5.3.jpg",
        "images/page-images/5/5.4.jpg",
        "images/page-images/5/5.5.jpg",
      ],
      url: "properties/prop6.html",
      added: {
        month: "June",
        day: 15,
        year: 2022,
      },
    },
    {
      id: "prop7",
      type: "House",
      bedrooms: 5,
      title: "Luxury House in Ella",
      price: 1250000,
      tenure: "Freehold",
      description:
        "Boasting free bikes, a garden as well as a terrace, Berghause Bungalow is situated in Ella, 5.6 km from Demodara Nine Arch Bridge. The property is around 48 km from Hakgala Botanical Garden, 1.7 km from Demodara Railway Station and 8.2 km from Ella Railway Station. The accommodation features a shared kitchen and room service for guests.",
      location:
        "No 80, Netherville Road, Ella, Demodara., 90080 Ella, Sri LankaAfter booking, all of the property’s details, including telephone and address, are provided in your booking confirmation and your account.",
      picture: "images/page-images/6/6.1.jpg",
      picturePanel: [
        "images/page-images/6/6.1.jpg",
        "images/page-images/6/6.2.jpg",
        "images/page-images/6/6.3.jpg",
        "images/page-images/6/6.4.jpg",
        "images/page-images/6/6.5.jpg",
      ],
      url: "properties/prop7.html",
      added: {
        month: "May",
        day: 23,
        year: 2022,
      },
    },
    {
      id: "prop8",
      type: "Apartment",
      bedrooms: 2,
      title: "The Residence",
      price: 420000,
      tenure: "Leasehold",
      description:
        "Well-presented two-bedroom apartment with a private balcony and parking space.",
      location: "No. 44/10 Dhammadassi Mawatha, 20000 Kandy, Sri Lanka",
      picture: "images/page-images/7/7.1.jpg",
      picturePanel: [
        "images/page-images/7/7.1.jpg",
        "images/page-images/7/7.2.jpg",
        "images/page-images/7/7.3.jpg",
        "images/page-images/7/7.4.jpg",
        "images/page-images/7/7.5.jpg",
      ],
      url: "properties/prop8.html",
      added: {
        month: "April",
        day: 5,
        year: 2022,
      },
    },
    {
      id: "prop9",
      type: "Flat",
      title: "Private Apartment in Colombo 5",
      bedrooms: 3,
      price: 475000,
      tenure: "Leasehold",
      description:
        "Set in Colombo, 2.4 km from Wellawatte Beach and 2.5 km from Milagiriya Beach, Private Apartment in Colombo 5 offers air conditioning. This property offers a private pool and free private parking. The property is non-smoking and is situated 3.7 km from Bambalapitiya Railway Station.",
      location: "35 Thalakotuwa Gardens, 00500 Colombo, Sri Lank",
      picture: "images/page-images/8/8.1.jpg",
      picturePanel: [
        "images/page-images/8/8.1.jpg",
        "images/page-images/8/8.2.jpg",
        "images/page-images/8/8.3.jpg",
        "images/page-images/8/8.4.jpg",
        "images/page-images/8/8.5.jpg",
      ],
      url: "properties/prop9.html",
      added: {
        month: "March",
        day: 30,
        year: 2022,
      },
    },
    {
      id: "prop10",
      type: "House",
      bedrooms: 6,
      price: 1850000,
      tenure: "Freehold",
      description:
        "Stunning six-bedroom period property with character features, extensive gardens, and ample parking.",
      location: "Shoreham Village, Sevenoaks TN14",
      picture: "images/page-images/9/9.1.jpeg",
      picturePanel: [
        "images/page-images/9/9.1.jpeg",
        "images/page-images/9/9.2.jpeg",
        "images/page-images/9/9.3.jpeg",
        "images/page-images/9/9.4.jpeg",
        "images/page-images/9/9.5.jpeg",
        "images/page-images/9/9.6.jpeg",
        "images/page-images/9/9.7.jpeg",
        "images/page-images/9/9.8.jpeg",
        "images/page-images/9/9.9.jpeg",
        "images/page-images/9/9.10.jpeg",
      ],
      url: "properties/prop10.html",
      added: {
        month: "February",
        day: 18,
        year: 2022,
      },
    },
  ],
};
